# POST http://localhost:9080/api/user/register
POST http://localhost:9080/register HTTP/1.1 

Content-Type: application/json 

{ 
  "name": "rehan", 
  "userName": "rehan", 
  "email": "rehan@gmail.com", 
  "password": "1234567" 
} 

### To Login User  
POST http://localhost:9080/register HTTP/1.1 

Content-Type: application/json 

{ 
    "password":"1234567", 
    "email":"asif@gmail.com" 
} 